/*
 * File: app/store/departureTimes.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.departureTimes', {
    extend: 'Ext.data.Store',

    config: {
        storeId: 'departureTimes',
        proxy: {
            type: 'ajax',
            url: '/fs-et/api.php',
            reader: {
                type: 'json',
                rootProperty: 'departures'
            }
        },
        fields: [
            {
                name: 'countdown'
            },
            {
                name: 'direction'
            },
            {
                name: 'line'
            },
            {
                name: 'platform'
            },
            {
                name: 'realtime'
            },
            {
                name: 'timetable'
            }
        ]
    },

    constructor: function() {
        var me = this;
        me.callParent(arguments);
        me.getProxy().on([{
            fn: 'onAjaxproxyException',
            event: 'exception',
            scope: me
        }]);
    },

    onAjaxproxyException: function(server, response, operation, options) {
        alert("Problem loading data, please retry.");
    }

});