/*
 * File: app/store/Stations.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Stations', {
    extend: 'Ext.data.Store',

    config: {
        autoLoad: true,
        pageSize: 1000,
        storeId: 'stations',
        proxy: {
            type: 'ajax',
            url: '/allByName',
            reader: {
                type: 'json',
                rootProperty: 'rows',
                totalProperty: 'total_rows'
            }
        },
        fields: [
            {
                name: 'id'
            },
            {
                name: 'key'
            },
            {
                name: 'value'
            },
            {
                name: 'group'
            }
        ],
        grouper: {
            groupFn: function(record) {
                if(record.get("group") !== undefined)
                return record.get("group");
                return record.get("key").split(" / ")[0];
            }
        }
    }
});